ruleset:

  close:
  
    name: Close issues
    events: [ issues, pull_request ]
    when:
      - action = "opened"
    close: true

  reopen:

    name: Allow issue/PR creator to reopen issues
    events: [ issue_comment ]
    when:
      - comment.user.login in [issue.user.login, pull_request.user.login]
      - comment.body contains '/reopen'
    reopen: true
