ruleset:

  close:
  
    name: Close issues
    events: [ issues ]
    when:
      - action = "opened"
    close: true

  reopen:

    name: Allow issue/PR creator to reopen issues
    events: [ issue_comment ]
    when:
      #- issue.user.login = comment.user.login
      - comment.body contains '/reopen'
